describe("My first test", function () {
  it("Answers questions and gets correct feedbacks", function () {
    cy.visit("localhost:3000?testMode=true");
    cy.questionIs("lithiase");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(0, true);
    cy.goToNextQuestion();
    cy.questionIs("dipygus");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(1, true);
    cy.goToNextQuestion();
    cy.questionIs("porphyrie");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(2, true);
    cy.goToNextQuestion();
    cy.questionIs("apraxie");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(3, true);
    cy.goToNextQuestion();
    cy.questionIs("arythmie");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(4, true);
    cy.goToNextQuestion();
    cy.playAgain();
    cy.questionIs("lipogramme");
    cy.answerFigure();
    cy.shouldBeGoodAnswer(0, true);
    cy.goToNextQuestion();
    cy.questionIs("amphibologie");
    cy.answerFigure();
    cy.shouldBeGoodAnswer(1, true);
    cy.goToNextQuestion();
    cy.questionIs("hystérologie");
    cy.answerFigure();
    cy.shouldBeGoodAnswer(2, true);
    cy.goToNextQuestion();
    cy.questionIs("éthopée");
    cy.answerFigure();
    cy.shouldBeGoodAnswer(3, true);
    cy.goToNextQuestion();
    cy.questionIs("symploque");
    cy.answerPathologie();
    cy.shouldBeGoodAnswer(4, false);
    cy.goToNextQuestion();
    cy.contains("Rejouer au jeu");
    cy.playAgain();
    cy.questionIs("lithiase");
  });
});
